apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-sim-deployment
  labels:
    app: fleet-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-sim
  template:
    metadata:
      labels:
        app: fleet-sim
    spec:
      containers:
      - name: fleet-sim
        image: patrickmeyer/fleet_sim:0.1
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT 
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_PORT
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGODB_HOST
        - name: MONGODB_PORT 
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGODB_PORT
