apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-sim-deployment
  labels:
    app: fleet-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-sim
  template:
    metadata:
      labels:
        app: fleet-sim
    spec:
      containers:
      - name: fleet-sim
        image: patrickmeyer/fleet-sim:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_HOST_INTERNAL
        - name: RABBITMQ_PORT 
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_PORT
        - name: FASTAPI_HOST 
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: FASTAPI_HOST
        - name: FASTAPI_PORT 
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: FASTAPI_PORT