apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: gui
      port: 15672
      targetPort: 15672
    - protocol: TCP
      name: api
      port: 5672
      targetPort: 5672
  type: NodePort