apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: <Name des initialen RabbitMQ Nutzers base64 enkodiert> 
  RABBITMQ_DEFAULT_PASS: <Initiales RabbitMQ Passwort base64 enkodiert> 