apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: <base64 enkodierter String>
  POSTGRES_USER: <base64 enkodierter String>
  POSTGRES_PASSWORD: <base64 enkodierter String>
