apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: <Name der DB base64 enkodiert> 
  POSTGRES_USER: <Name des initialen PostgreSQL Nutzers base64 enkodiert> 
  POSTGRES_PASSWORD: <Initiales PostgreSQL Passwort base64 enkodiert> 